# Generated by Django 5.0.1 on 2024-05-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0003_alter_email_id_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
